# Generated by Django 6.0.3 on 2026-03-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_complaint_sla_ticket_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="assigned_team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("support", "Support Team"),
                    ("technical", "Technical Team"),
                    ("billing", "Billing Team"),
                ],
                max_length=20,
            ),
        ),
    ]
